version: '3.8'

services:
  mongo:
    container_name: fnote-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: fnote
      MONGO_INITDB_ROOT_PASSWORD: fnote
      MONGO_INITDB_DATABASE: fnote
      # 部署前请修改用户名和密码
      MONGO_USERNAME: fnote-user
      MONGO_PASSWORD: fnote-password
    volumes:
      - /fnote/mongo_data:/data/db
      - ./script/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./script/mongo-data-init.sh:/docker-entrypoint-initdb.d/mongo-data-init.sh
    ports:
      - "27017:27017"
    command:
      - --auth
  server:
    container_name: fnote-server
    image: fnote/fnote-server:latest
    build:
      dockerfile: Dockerfile
      context: ./server
      args:
        # 修改成你的网站域名
        WEBSITE_DOMAIN: https://xxx.com
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - /fnote/logs:/fnote/logs
      - /fnote/static:/fnote/static
  web:
    container_name: fnote-web
    image: fnote/fnote-web:latest
    build: 
      dockerfile: Dockerfile
      context: ./web
      args:
        # 修改成你的网站域名
        WEBSITE_DOMAIN: https://xxx.com
    ports:
      - "3000:3000"
    depends_on:
      - server