version: '3.8'

services:
  mongo:
    container_name: local-fnote-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: fnote
      MONGO_INITDB_ROOT_PASSWORD: fnote
      MONGO_INITDB_DATABASE: fnote
      MONGO_USERNAME: fnote-user
      MONGO_PASSWORD: fnote-password
    volumes:
      - /tmp/fnote/mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongo-data-init.sh:/docker-entrypoint-initdb.d/mongo-data-init.sh
    ports:
      - "27017:27017"
    command:
      - --auth