# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: fnote-Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Get dependencies
        run: |
          cd backend
          go mod download
    - name: Build
      working-directory: ./backend
      run: go build -v ./...

    - name: Test
      working-directory: ./backend
      run: go test -race -coverprofile=cover.out -v ./...
